CRITICAL - 2023-12-07 05:53:45 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 28.
 1 APPPATH\Views\maestros\listacontratos.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 28)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(15): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 05:56:27 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 28.
 1 APPPATH\Views\maestros\listacontratos.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 28)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(15): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:06:33 --> mysqli_sql_exception: No database selected in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}
CRITICAL - 2023-12-07 06:06:33 --> No database selected
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tu_tabla`', [], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:06:36 --> mysqli_sql_exception: No database selected in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}
CRITICAL - 2023-12-07 06:06:36 --> No database selected
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tu_tabla`', [], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:08:14 --> mysqli_sql_exception: No database selected in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}
CRITICAL - 2023-12-07 06:08:14 --> No database selected
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:08:19 --> mysqli_sql_exception: No database selected in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}
CRITICAL - 2023-12-07 06:08:19 --> No database selected
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:10:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:10:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:11:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:11:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:11:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:11:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:13:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:13:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:13:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:13:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:14:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:14:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:14:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:14:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:14:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:14:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:15:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:15:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:15:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:15:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 06:32:29 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 31.
 1 APPPATH\Views\maestros\listacontratos.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 31)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(20): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:33:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:33:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:40:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:40:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 06:58:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(82): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(82): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 06:58:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(82): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:00:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:00:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(86): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:00:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:00:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(86): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:01:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:01:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(86): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:01:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(86): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:01:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(86): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:05:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:05:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(18): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 07:07:46 --> Undefined variable $variable_no_definida
in APPPATH\Controllers\Maestros.php on line 19.
 1 APPPATH\Controllers\Maestros.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $variable_no_definida', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Controllers\\Maestros.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 07:08:10 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 31.
 1 APPPATH\Views\maestros\listacontratos.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 31)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(23): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 07:08:17 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 31.
 1 APPPATH\Views\maestros\listacontratos.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 31)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(23): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:09:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:09:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:09:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:09:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 07:09:44 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 31.
 1 APPPATH\Views\maestros\listacontratos.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 31)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(23): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 07:09:45 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 31.
 1 APPPATH\Views\maestros\listacontratos.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 31)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(23): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 07:10:02 --> Undefined variable $contratos
in APPPATH\Views\maestros\listacontratos.php on line 31.
 1 APPPATH\Views\maestros\listacontratos.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contratos', 'C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php', 31)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\app\\Views\\maestros\\listacontratos.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('maestros/listacontratos', [], true)
 5 APPPATH\Controllers\Maestros.php(23): view('maestros/listacontratos')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:10:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:10:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:14:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:14:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:17:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:17:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:17:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:17:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:19:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:19:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:19:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:19:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:21:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#12 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}
CRITICAL - 2023-12-07 07:21:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\ContratoModel.php(13): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Maestros.php(21): App\Models\ContratoModel->obtenerContratos()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:23:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(31): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(31): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#11 {main}
CRITICAL - 2023-12-07 07:23:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Maestros.php(31): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:23:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(31): CodeIgniter\BaseModel->findAll()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(31): CodeIgniter\BaseModel->findAll()
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#10 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#11 {main}
CRITICAL - 2023-12-07 07:23:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contratos`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Maestros.php(31): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:26:59 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#8 {main}
CRITICAL - 2023-12-07 07:26:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM contratos')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:28:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\PruebaConexion.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\PruebaConexion->index()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaConexion))
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\PruebaConexion.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\PruebaConexion->index()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaConexion))
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#8 {main}
CRITICAL - 2023-12-07 07:28:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\PruebaConexion.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM contratos')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\PruebaConexion->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaConexion))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:39:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#8 {main}
CRITICAL - 2023-12-07 07:39:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM contratos')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:45:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#8 {main}
CRITICAL - 2023-12-07 07:45:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM contratos')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
ERROR - 2023-12-07 07:46:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sap_fiducias', 3306, '', 0)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#8 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\app\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#3 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
#4 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
#5 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\public\index.php(88): CodeIgniter\CodeIgniter->run()
#7 C:\Users\ip3\Documents\SAPIENCIA\Fiducias\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Do...')
#8 {main}
CRITICAL - 2023-12-07 07:46:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Maestros.php(23): CodeIgniter\Database\BaseConnection->query('SELECT * FROM contratos')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
CRITICAL - 2023-12-07 08:16:49 --> Object of class App\Models\ContratoModel could not be converted to string
in APPPATH\Controllers\Maestros.php on line 38.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Maestros->contratos('1')
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maestros))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(88): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\ip3\\Documents\\SAPIENCIA\\Fiducias\\public\\index.php')
